package application.modules;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;

import javafx.scene.shape.Circle;

import javafx.scene.layout.GridPane;

public class HostCardViewController {
	@FXML private Text nameTxt, dayTxt, dateTxt, timeTxt, playerCountTxt, sportTxt;
	@FXML private JFXButton joinBtn;
	@FXML private Circle playerCountCircle;
	@FXML private GridPane profileGridPane, rootGridPane;

	// Event Listener on Pane.onMouseClicked
	@FXML
	public void hostCardOnMouseClick(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton.onAction
	@FXML
	public void joinBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
