package application;

import javafx.fxml.FXML;

import com.jfoenix.controls.JFXButton;
import javafx.event.ActionEvent;

public class NavigationViewController {
	@FXML
	private JFXButton navProfileBtn;
	@FXML
	private JFXButton navPlayBtn;
	@FXML
	private JFXButton navFriendsBtn;
	@FXML
	private JFXButton navRatingsBtn;
	@FXML
	private JFXButton navNotiBtn;
	@FXML
	private JFXButton navLogoutBtn;

	@FXML
	public void initialize() {
		if (Main.getLoc().getPath().contains("ProfileView.fxml")) {
			navProfileBtn.getStyleClass().add("active");
		}
		else {
			navProfileBtn.getStyleClass().removeAll("active");
		}
	}
	
	// Event Listener on JFXButton[#navProfileBtn].onAction
	@FXML
	public void navProfileBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#navPlayBtn].onAction
	@FXML
	public void navPlayBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#navFriendsBtn].onAction
	@FXML
	public void navFriendsBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#navRatingsBtn].onAction
	@FXML
	public void navRatingsBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#navNotiBtn].onAction
	@FXML
	public void navNotiBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#navLogoutBtn].onAction
	@FXML
	public void navLogoutBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
