package application;

import java.net.URL;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.layout.GridPane;

import dataAccess.AccountsDA;

public class NavigationViewController implements Initializable {
	@FXML private JFXButton navProfileBtn, navPlayBtn, navFriendsBtn, navRatingsBtn, navNotiBtn, navLogoutBtn;
	@FXML private GridPane rootPane;

	private final URL lrfViewURL = getClass().getResource("/application/LRFView.fxml");
	private final URL profileViewURL = getClass().getResource("/application/ProfileView.fxml");
	private final URL findGameURL = getClass().getResource("/application/FindAGame.fxml");
	
	public static int HostAGame_index = 0;

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		if (Main.getLoc().getPath().contains("/ProfileView.fxml")) {
			navProfileBtn.getStyleClass().add("active");
		}
		else {
			navProfileBtn.getStyleClass().removeAll("active");
		}
	}

	// Event Listener on JFXButton[#navProfileBtn].onAction
	@FXML
	public void navProfileBtnOnAction(ActionEvent event) {
		try {
			Main.getRoot().setCenter(FXMLLoader.load(profileViewURL));
		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Event Listener on JFXButton[#navPlayBtn].onAction
	@FXML
	public void navPlayBtnOnAction(ActionEvent event) {
		try {
			Main.getRoot().setCenter(FXMLLoader.load(findGameURL));
		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Event Listener on JFXButton[#navFriendsBtn].onAction
	@FXML
	public void navFriendsBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#navRatingsBtn].onAction
	@FXML
	public void navRatingsBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#navNotiBtn].onAction
	@FXML
	public void navNotiBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#navLogoutBtn].onAction
	@FXML
	public void navLogoutBtnOnAction(ActionEvent event) {
		AccountsDA.logout();

		if (AccountsDA.getSession() == null) {
			try {
				Main.getRoot().setCenter(FXMLLoader.load(lrfViewURL));
				Main.getRoot().setBottom(null);
			}
			catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
}
