package application;

import javafx.fxml.FXML;
import javafx.scene.text.Text;

import entity.NotificationsEntity;

import dataAccess.NotificationsDA;

import modules.Misc;

import java.time.LocalDateTime;
import java.util.List;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;
import javafx.scene.Cursor;
import javafx.scene.control.Label;

import javafx.scene.layout.GridPane;

public class NotificationController {
	@FXML private GridPane notiGridPane;
	@FXML private Label lblStatus;
	@FXML private Text lblNotification;
	@FXML private GridPane profileGridPane;
	@FXML private Label lblName;
	@FXML private Text txtIcon;
	@FXML private JFXButton yesButton;

	private int i = NotificationViewController.getNotiIndex();
	private List<NotificationsEntity> notifications = NotificationViewController.getNotification();

	private String adminNo = notifications.get(i).getAdminNo();
	private String name = notifications.get(i).getName();
	private String sports = notifications.get(i).getSports();
	private String venue = notifications.get(i).getLocation();
	private LocalDateTime dateTime = notifications.get(i).getDateTime();
	private int status = notifications.get(i).getStatus();
	
	private String fNameToUpper = name.replace(name.charAt(0), name.toUpperCase().charAt(0));
	
	@FXML
	private void initialize() {
		lblName.setText(fNameToUpper);
		
		switch (status) {
			case 0:
				lblStatus.setText("Invitation");
				txtIcon.setText("");
				lblNotification.setText(fNameToUpper + " has invited you to a game of " + sports + " \nat the " + venue + " on " + dateTime);
				//JFXButton noBtn = new JFXButton("No");
				//noBtn.getStyleClass().add("danger");
				//noBtn.setCursor(Cursor.HAND);
				break;
			case 1:
				lblStatus.setText("Joined");
				txtIcon.setText("");
				lblNotification.setText(fNameToUpper + " has joined your game of " + sports + " \nat the " + venue + " on " + dateTime);
				break;
			case 2:
				lblStatus.setText("Rating");
				lblNotification.setText("You have pending rating");
				break;
			case 3:
				lblStatus.setText("Friend Request");
				lblNotification.setText(adminNo + ", " + fNameToUpper + " has sent you a friend request");
				break;
		}
		profileGridPane.add(new Misc().cropCirclePhoto(adminNo, 100), 0, 0);
	}

	// Event Listener on JFXButton.onAction
	@FXML
	public void yesBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
