package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.text.Text;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.shape.Circle;

import javafx.scene.layout.GridPane;

public class NotificationController implements Initializable {
	@FXML private GridPane notiGridPane;
	@FXML private Label lblStatus;
	@FXML private Text lblNotification;
	@FXML private GridPane profileGridPane;
	@FXML private Circle circlePicture;
	@FXML private Label lblName;
	@FXML private Text txtIcon;

	private int i = NotificationViewController.getNotiIndex();
	private Object[][] notifications = NotificationViewController.getNotifications();

	private String adminNo = (String) notifications[i][0];
	private String name = (String) notifications[i][1];
	private String sports = (String) notifications[i][2];
	private String venue = (String) notifications[i][3];
	private String date = (String) notifications[i][4];
	private String time = (String) notifications[i][5];
	private int status = (int) notifications[i][6];

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		lblName.setText(name);

		switch (status) {
			case 0:
				lblStatus.setText("Invitation");
				lblNotification.setText(name + " has invited you to a game of " + sports + " at the " + venue + " on " + date + " " + time);
				break;
			case 1:
				lblStatus.setText("Joined");
				lblNotification.setText(name + " has joined your game of " + sports + " at the " + venue + " on " + date + " " + time);
				break;
			case 2:
				lblStatus.setText("Rating");
				lblNotification.setText("You have pending rating");
				break;
			case 3:
				lblStatus.setText("Friend Request");
				lblNotification.setText(adminNo + ", " + name + " has sent you a friend request");
				break;
		}
	}

	// Event Listener on JFXButton.onAction
	@FXML
	public void yesBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
