package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.text.Text;

import entity.NotificationsEntity;

import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.shape.Circle;

import javafx.scene.layout.GridPane;

public class NotificationController implements Initializable {
	@FXML private GridPane notiGridPane;
	@FXML private Label lblStatus;
	@FXML private Text lblNotification;
	@FXML private GridPane profileGridPane;
	@FXML private Circle circlePicture;
	@FXML private Label lblName;
	@FXML private Text txtIcon;

	private int i = NotificationViewController.getNotiIndex();
	private List<NotificationsEntity> notifications = NotificationViewController.getNotification();

	private String adminNo = notifications.get(i).getAdminNo();
	private String name = notifications.get(i).getName();
	private String sports = notifications.get(i).getSports();
	private String venue = notifications.get(i).getLocation();
	private String date = notifications.get(i).getDate();
	private String time = notifications.get(i).getTime();
	private int status = notifications.get(i).getStatus();

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		lblName.setText(name);

		switch (status) {
			case 0:
				lblStatus.setText("Invitation");
				lblNotification.setText(name + " has invited you to a game of " + sports + " \nat the " + venue + " on " + date + " " + time);
				break;
			case 1:
				lblStatus.setText("Joined");
				lblNotification.setText(name + " has joined your game of " + sports + " \nat the " + venue + " on " + date + " " + time);
				break;
			case 2:
				lblStatus.setText("Rating");
				lblNotification.setText("You have pending rating");
				break;
			case 3:
				lblStatus.setText("Friend Request");
				lblNotification.setText(adminNo + ", " + name + " has sent you a friend request");
				break;
		}
	}

	// Event Listener on JFXButton.onAction
	@FXML
	public void yesBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
