package application;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;

import javafx.scene.shape.Circle;

public class ProfileViewController {
	@FXML
	private Circle dpCircle;
	@FXML
	private Text nameTxt;
	@FXML
	private Text heightWeightTxt;
	@FXML
	private Text ratingStarsTxt;
	@FXML
	private Text matchNoTxt;
	@FXML
	private JFXButton editBtn;
	@FXML
	private Text introTxt;

	// Event Listener on JFXButton[#editBtn].onAction
	@FXML
	public void editBtnOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
