package application;

import javafx.fxml.FXML;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;

import javafx.scene.shape.Circle;

public class RatingsProfileController {
	@FXML
	private Label eventDay;
	@FXML
	private Label eventDate;
	@FXML
	private Label eventTime;
	@FXML
	private Label sportsType;
	@FXML
	private JFXButton rateBtn;
	@FXML
	private Circle circularMeter;
	@FXML
	private Label noOfplayers;
	@FXML
	private Circle hostDP;
	@FXML
	private Label hostName;

	// Event Listener on JFXButton[#rateBtn].onAction
	@FXML
	
//	public void initialize() throws IOException {
//		
//		RatingsDA.initDA();
//		for (int i = 0; i < HostsDA.returnHostsList().size(); i++) {
//			infoDisplayField.add(FXMLLoader.load(getClass().getResource("/application/FindAGame_space.fxml")), 1, ++i);
//			infoDisplayField.add(FXMLLoader.load(getClass().getResource("/application/RatingsProfile.fxml")), 1, ++i);
//			
//		}
//	}
	public void handleRate(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#noOfplayers].onMouseClicked
	@FXML
	public void handleNoOfPlayersRecruited(MouseEvent event) {
		// TODO Autogenerated
	}
}
