package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.geometry.Pos;

import java.net.URL;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.shape.Circle;


public class RatingsProfileController implements Initializable {
	@FXML
	private Label eventDay;
	@FXML
	private Label eventDate;
	@FXML
	private Label eventTime;
	@FXML
	private Label sportsType;
	@FXML
	private JFXButton rateBtn;
	@FXML
	private Circle circularMeter;
	@FXML
	private Label noOfplayers;
	@FXML
	private Circle hostDP;
	@FXML
	private Label hostName;

	// Event Listener on JFXButton[#rateBtn].onAction
	@FXML

	
	public void handleRate(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#noOfplayers].onMouseClicked
	@FXML
	public void handleNoOfPlayersRecruited(MouseEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub

	}
}
